CREATE TABLE IF NOT EXISTS 'users' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 'username' TEXT NOT NULL, 'hash' TEXT NOT NULL, 'cash' NUMERIC NOT NULL DEFAULT 10000.00 );
CREATE TABLE sqlite_sequence(name,seq);
CREATE UNIQUE INDEX 'username' ON "users" ("username");
CREATE INDEX 'user_id' on "users" ("user_id");
CREATE TABLE IF NOT EXISTS 'stocks' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,'user_id' INTEGER, 'symbol' TEXT NOT NULL, 'name' TEXT NOT NULL, 'shares' INTEGER NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS 'purchases' ('id' INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,'user_id' INTEGER, 'symbol' TEXT NOT NULL, 'name' TEXT NOT NULL, 'shares' INTEGER NOT NULL, 'price' NUMERIC NOT NULL, 'total' NUMERIC NOT NULL, 'date' TEXT NOT NULL, FOREIGN KEY(user_id) REFERENCES users(id));
